# Generated by Django 5.2.9 on 2026-02-16 15:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='students/photos/')),
                ('date_of_birth', models.DateField()),
                ('date_joined', models.DateField(default=django.utils.timezone.now)),
                ('student_class', models.CharField(help_text='Current class/grade', max_length=100)),
                ('interests', models.TextField(blank=True, null=True)),
                ('talents', models.TextField(blank=True, null=True)),
                ('health_status', models.TextField(blank=True, help_text='General health condition and allergies', null=True)),
                ('core_values', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('programs_enrolled', models.ManyToManyField(blank=True, related_name='students', to='programs.program')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Year 2025 Term 1 Report', max_length=255)),
                ('file', models.FileField(upload_to='students/transcripts/')),
                ('description', models.TextField(blank=True, null=True)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='students.student')),
            ],
        ),
    ]
