# Generated by Django 4.2.7 on 2025-12-06 14:37

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('education', 'Education'), ('healthcare', 'Healthcare'), ('nutrition', 'Nutrition'), ('mentorship', 'Mentorship'), ('recreation', 'Recreation'), ('shelter', 'Shelter'), ('other', 'Other')], max_length=20)),
                ('short_description', models.TextField(max_length=500)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='programs/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='programs/banners/')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('upcoming', 'Upcoming'), ('completed', 'Completed')], default='active', max_length=20)),
                ('target_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('beneficiaries_count', models.PositiveIntegerField(default=0)),
                ('volunteers_needed', models.PositiveIntegerField(default=0)),
                ('features', models.JSONField(default=list, help_text='List of program features')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='program_updates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='programs.program')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='beneficiaries/')),
                ('story', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('joined_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='programs.program')),
            ],
        ),
    ]
